POST http://localhost:8080/restservices/list
Content-Type: application/json



###
POST http://localhost:8080/restservices/authenticatie
Content-Type: application/json

{
  "username" : "stront",
  "password" : "123"
}

###
GET http://localhost:8080/restservices/list
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJzdHJvbnQiLCJleHAiOjE2NTQ2MDUwOTgsInJvbGUiOiJhZG1pbiJ9.VqvkDAi0bYbdwfZmIhj8AlXrfvJR-m2afaFtMAtstUhPke1I7jMBXPb6oqUCa2xaW3l8XqWS5kw_PGrReP0ZBQ




