POST http://localhost:8080/restservices/list
Content-Type: application/json



###
POST http://localhost:8080/restservices/authenticatie
Content-Type: application/json

{
  "username" : "stront",
  "password" : "123"
}

###
GET http://localhost:8080/restservices/list
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJzdHJvbnQiLCJleHAiOjE2NTQxNjk3NzgsInJvbGUiOiJhZG1pbiJ9.hq6bCHemKU8x3LzvURTAM98aZusTcBMFibSyTR57JW3stnIr11-H3-_hS3iNDFOsrheynZ8kwUNVypqqueR1JQ




